[package]
name = "picarlo"
version = "0.4.1"
edition = "2021"

[lib]
name = "_picarlo_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.3", features = ["extension-module"] }
rand = "0.8.5"
